const DB_KEY = 'greenpaper_demo_db_v3';
const AUTH_KEY = 'greenpaper_auth_v3';
const USERS_KEY = 'greenpaper_users_v3';

const APP = {
  state: {
    route: location.hash.replace('#','') || 'dashboard',
    search: '',
    filters: {},
    modal: null,
    user: loadAuth(),
    sapSync: { status: 'CONNECTING', lastSync: null, nextSync: null, employeeCounts: {}, error: null, inFlight: false },
  },
  icons: {
    dashboard:'⌂', customers:'◉', enquiries:'◌', quotations:'▤', orders:'▣', approvals:'✓',
    inventory:'◫', production:'⚙', quality:'◍', dispatch:'⇧', delivery:'⌁', invoices:'▧',
    payments:'₹', reports:'▥', profile:'◯', settings:'⚙'
  }
};

const ROLES = ['Sales Manager','Production','Management'];

function deepClone(value){ return JSON.parse(JSON.stringify(value)); }
function loadAuth(){ try { return JSON.parse(localStorage.getItem(AUTH_KEY)) || null; } catch { return null; } }
function getUsers(){ try { return JSON.parse(localStorage.getItem(USERS_KEY)) || []; } catch { return []; } }
function setUsers(users){ localStorage.setItem(USERS_KEY, JSON.stringify(users)); }
function saveAuth(user){ APP.state.user=user; if(user) localStorage.setItem(AUTH_KEY,JSON.stringify(user)); else localStorage.removeItem(AUTH_KEY); }
function escapeHtml(value){ return String(value ?? '').replace(/[&<>"']/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m])); }
function money(n){ return '₹'+Number(n||0).toLocaleString('en-IN'); }
function fmtDate(d){ if(!d) return '—'; const x=new Date(d); return Number.isNaN(x.getTime()) ? d : x.toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}); }
function nowDate(){ return new Date().toISOString().slice(0,10); }
function nowTime(){ return new Date().toTimeString().slice(0,8); }
function setSapSyncState(patch){ APP.state.sapSync={...APP.state.sapSync,...patch}; }
function sapStatusLabel(){const s=APP.state.sapSync.status;return s==='CONNECTED'?'Connected':s==='SYNCING'?'Synchronizing…':s==='ERROR'?'Connection error':'Connecting…';}
function sapStatusClass(){const s=APP.state.sapSync.status;return s==='CONNECTED'?'green':s==='ERROR'?'red':'amber';}
function sapDateTime(v){return v?new Date(v).toLocaleString('en-IN',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'}):'Not synchronized yet';}
function ensureSapCustomer(row){const k=String(row.KUNNR||'').trim();const name=String(row.NAME1||'').trim()||`SAP Customer ${k||'Unknown'}`;if(!k)return {id:'SAPC-UNKNOWN',name,code:'—'};let c=APP.db.customers.find(x=>x.sapKunnr===k||x.id===`SAPC-${k}`);if(!c){c={id:`SAPC-${k}`,sapKunnr:k,code:k,name,gst:'—',city:'—',terms:'—',owner:row.ZNAME11||'SAP',outstanding:0,status:'Active'};APP.db.customers.push(c);}else{c.name=name;c.owner=row.ZNAME11||c.owner;}return c;}
function ensureSapProduct(row){const m=String(row.MATNR||'').trim();if(!m)return {id:'SAP-PRODUCT-UNKNOWN',name:String(row.ARKTX||'SAP Product'),code:'—',grade:'SAP',gsm:'—',size:'—',form:'SAP',finish:'—',unit:String(row.VRKME||'')||'EA',rate:Number(row.NETPR||0)};let p=APP.db.products.find(x=>x.sapMatnr===m||x.id===`SAP-${m}`);if(!p){p={id:`SAP-${m}`,sapMatnr:m,code:m,name:String(row.ARKTX||m),grade:'SAP',gsm:'—',size:'—',form:'SAP',finish:'—',unit:String(row.VRKME||'')||'EA',rate:Number(row.NETPR||0)};APP.db.products.push(p);}else{p.name=String(row.ARKTX||p.name);p.unit=String(row.VRKME||p.unit);p.rate=Number(row.NETPR||0);}return p;}
function normalizeSapApproval(order,a){if(a){const raw=String(a.STATUS??'').trim().toUpperCase();order.approvalStatus=raw==='A'?'APPROVED':raw==='R'?'REJECTED':raw==='P'?'PENDING':raw||'UNKNOWN';order.sapApprovalStatus=raw||'—';order.approvalUser=a.USERNAME||'';order.approvalDate=a.ZDATE||'';order.approvalTime=a.ZTIME||'';order.sapApprovalCode=a.ACODE||order.sapApprovalCode||'';order.sapApprovalUser=a.ZNAME11||order.sapApprovalUser||'';}else{const z=String(order.sapZname||'').toUpperCase();order.approvalStatus=z.includes('NOT APPROVED')||z.includes('APPROVAL')?'PENDING':order.approvalStatus||'UNKNOWN';}}
function upsertSapOrders(rows,approvals,employee){const groups=new Map();(Array.isArray(rows)?rows:[]).forEach((r,i)=>{const v=String(r.VBELN||'').trim();if(v){if(!groups.has(v))groups.set(v,[]);groups.get(v).push({...r,__rowIndex:i});}});const amap=new Map();(Array.isArray(approvals)?approvals:[]).forEach(a=>{const v=String(a.VBELN||'').trim();if(v)amap.set(v,a);});let count=0;groups.forEach((lines,vbeln)=>{const first=lines[0],c=ensureSapCustomer(first);let o=APP.db.orders.find(x=>x.sapNo===vbeln);const items=lines.map(r=>{const pr=ensureSapProduct(r);return {productId:pr.id,sapPosnr:r.POSNR??'',matnr:r.MATNR||'',description:r.ARKTX||pr.name,qty:Number(r.KWMENG||0),unit:r.VRKME||pr.unit,rate:Number(r.NETPR||0),netValue:Number(r.NETWR||0),discount:0,tax:0,raw:r};});const total=items.reduce((a,x)=>a+x.netValue,0);if(!o){o={id:`SO-SAP-${vbeln}`,sapNo:vbeln,source:'SAP',customerId:c.id,customerPO:first.BSTKD||'—',orderDate:first.AUDAT||first.ERDAT||'',deliveryDate:'',plant:first.WERKS||'—',subtotal:total,discount:0,tax:0,freight:0,total,orderStatus:'SAP',approvalStatus:'UNKNOWN',currentStage:null,syncStatus:'SYNCED',createdBy:first.ERNAM||first.ZNAME11||'SAP',items:[]};APP.db.orders.push(o);}Object.assign(o,{sapEmployee:employee,sapClient:first.MANDT||'100',customerId:c.id,customerPO:first.BSTKD||o.customerPO||'—',orderDate:first.AUDAT||first.ERDAT||o.orderDate,plant:first.WERKS||o.plant,subtotal:total,total,syncStatus:'SYNCED',createdBy:first.ERNAM||first.ZNAME11||o.createdBy,sapZname:first.ZNAME||'',sapStat:first.STAT||'',sapApprovalCode:first.ACODE||'',sapApprovalUser:first.ZNAME11||'',sapRows:lines.length});o.items=items;normalizeSapApproval(o,amap.get(vbeln));o.orderStatus=o.approvalStatus==='APPROVED'?'Approved':o.approvalStatus==='REJECTED'?'Rejected':o.approvalStatus==='PENDING'?'Pending Approval':'SAP';count++;});return count;}
async function fetchSapJson(url){const r=await fetch(url,{cache:'no-store'});const text=await r.text();let d;try{d=JSON.parse(text);}catch{throw new Error(`SAP returned non-JSON (${r.status})`);}if(!r.ok)throw new Error(d.error||`SAP request failed (${r.status})`);return d;}
async function syncSAP(silent=false){if(APP.state.sapSync.inFlight)return;setSapSyncState({status:'SYNCING',inFlight:true,error:null});if(!silent)toast('Synchronizing live SAP data…');render();try{const [a,b,soa]=await Promise.all([fetchSapJson('/api/sap/orders?employee=E0003'),fetchSapJson('/api/sap/orders?employee=E0006'),fetchSapJson('/api/sap/approvals')]);const approvals=Array.isArray(soa)?soa:(soa.data||[]);const c3=upsertSapOrders(Array.isArray(a)?a:(a.data||[]),approvals,'E0003');const c6=upsertSapOrders(Array.isArray(b)?b:(b.data||[]),approvals,'E0006');const last=new Date().toISOString(),next=new Date(Date.now()+15*60*1000).toISOString();setSapSyncState({status:'CONNECTED',lastSync:last,nextSync:next,employeeCounts:{E0003:c3,E0006:c6},inFlight:false,error:null});APP.db.sapConnection={status:'CONNECTED',lastSync:last,nextSync:next};APP.db.sapLastSync=last;saveDB();if(!silent)toast(`SAP sync completed • E0003: ${c3} • E0006: ${c6}`);render();}catch(err){setSapSyncState({status:'ERROR',inFlight:false,error:err.message});APP.db.sapConnection={status:'ERROR',lastSync:APP.state.sapSync.lastSync,error:err.message};saveDB();if(!silent)toast(`SAP sync failed: ${err.message}`,'error');render();}}
function startSapAutoSync(){syncSAP(true);setInterval(()=>syncSAP(true),15*60*1000);}
function customer(id){ return APP.db.customers.find(x=>x.id===id) || {name:'Unknown Customer',code:'—',gst:'—',city:'—',terms:'—',owner:'—',outstanding:0,status:'Active'}; }
function product(id){ return APP.db.products.find(x=>x.id===id) || {name:'Unknown Product',code:'—',grade:'—',gsm:'—',size:'—',form:'—',finish:'—',unit:'MT',rate:0}; }
function statusBadge(status){
  const s=String(status||'').toUpperCase(); let c='gray';
  if(['APPROVED','PASSED','PAID','DELIVERED','COMPLETED','AVAILABLE','SYNCED','DISPATCHED','ACTIVE'].includes(s)) c='green';
  else if(['IN PRODUCTION','IN TRANSIT','PARTIALLY DELIVERED','RAW MATERIAL ALLOCATED','QUALITY INSPECTION','READY','SCHEDULED'].includes(s)) c='blue';
  else if(['PENDING','DRAFT','SUBMITTED','PARTIALLY AVAILABLE','PARTIALLY PAID','STAGE_1_PENDING','STAGE_2_PENDING','STAGE_3_PENDING','PLANNED','NEW','SENT'].includes(s)) c='amber';
  else if(['REJECTED','FAILED','OVERDUE','DELAYED','CANCELLED','SYNC FAILED','SENT BACK','ON HOLD','SHORTAGE'].includes(s)) c='red';
  return `<span class="badge ${c}">${escapeHtml(status||'—')}</span>`;
}
function toast(message,type='success'){
  const root=document.getElementById('toast-root'); if(!root) return;
  root.innerHTML=`<div class="toast-msg ${type}">${escapeHtml(message)}</div>`;
  setTimeout(()=>{ root.innerHTML=''; },2800);
}
function audit(orderId,action,user){
  APP.db.audit.unshift({id:'LOG-'+Date.now(),orderId,action,user,time:`${nowDate()} ${nowTime()}`});
}

const seed = {
  customers: [
    {id:'C001',code:'CUST-1001',name:'ABC Packaging Pvt Ltd',gst:'27AABCA1234A1Z7',city:'Pune',terms:'30 Days',owner:'Rahul Mehta',status:'Active',outstanding:1284000},
    {id:'C002',code:'CUST-1002',name:'XYZ Papers & Boards',gst:'27AABXY5678B1Z9',city:'Mumbai',terms:'45 Days',owner:'Neha Shah',status:'Active',outstanding:742000},
    {id:'C003',code:'CUST-1003',name:'Metro Traders',gst:'27AACCM2234C1Z5',city:'Nagpur',terms:'30 Days',owner:'Arjun Rao',status:'Active',outstanding:396000},
    {id:'C004',code:'CUST-1004',name:'Global Packaging',gst:'29AABCG7788D1Z4',city:'Bengaluru',terms:'60 Days',owner:'Rahul Mehta',status:'Active',outstanding:1860000},
    {id:'C005',code:'CUST-1005',name:'Shree Enterprises',gst:'24AABCS9922E1Z3',city:'Ahmedabad',terms:'30 Days',owner:'Neha Shah',status:'On Hold',outstanding:280000}
  ],
  products: [
    {id:'P001',code:'PAP-KRF-120',name:'Kraft Paper',grade:'Natural Kraft',gsm:120,size:'1200 mm',form:'Reel',finish:'Machine Finished',unit:'MT',rate:68500},
    {id:'P002',code:'PAP-WHT-80',name:'Writing Paper',grade:'Maplitho',gsm:80,size:'880 x 620 mm',form:'Sheet',finish:'Smooth',unit:'MT',rate:74200},
    {id:'P003',code:'PAP-DUP-300',name:'Duplex Board',grade:'Grey Back',gsm:300,size:'730 x 1020 mm',form:'Sheet',finish:'Coated',unit:'MT',rate:61800},
    {id:'P004',code:'PAP-IND-150',name:'Industrial Paper',grade:'MG',gsm:150,size:'1250 mm',form:'Reel',finish:'Glazed',unit:'MT',rate:59200},
    {id:'P005',code:'PAP-COAT-100',name:'Coated Paper',grade:'Art Paper',gsm:100,size:'900 x 650 mm',form:'Sheet',finish:'Gloss',unit:'MT',rate:79800},
    {id:'P006',code:'PAP-KRF-90',name:'Light Kraft',grade:'Kraft',gsm:90,size:'1100 mm',form:'Reel',finish:'Machine Finished',unit:'MT',rate:64500},
    {id:'P007',code:'PAP-FLD-170',name:'Folding Box Board',grade:'FBB',gsm:170,size:'1020 x 720 mm',form:'Sheet',finish:'Coated',unit:'MT',rate:85200},
    {id:'P008',code:'PAP-TISS-24',name:'Tissue Base',grade:'Virgin',gsm:24,size:'1800 mm',form:'Reel',finish:'Soft',unit:'MT',rate:91500}
  ],
  enquiries: [], quotations: [], orders: [], approvals: [], inventory: [], production: [], quality: [], dispatches: [], deliveries: [], invoices: [], payments: [], audit: [], sap: [
    {MANDT:'100',VBELN:'0000100000',ZNAME11:'E0003',ACODE:'E0003',USERNAME:'SAB',ZDATE:'2026-09-20',ZTIME:'22:17:40',STATUS:'A',customerId:'C001'},
    {MANDT:'100',VBELN:'0000100001',ZNAME11:'E0007',ACODE:'E0007',USERNAME:'SAB',ZDATE:'2026-09-20',ZTIME:'18:40:22',STATUS:'A',customerId:'C002'},
    {MANDT:'100',VBELN:'0000100002',ZNAME11:'E0012',ACODE:'E0012',USERNAME:'SAB',ZDATE:'2026-09-21',ZTIME:'11:52:04',STATUS:'A',customerId:'C005'}
  ]
};

function makeBigCompanyData(db){
  const names=['Apex Packaging','NorthStar Papers','Prime Cartons','Sunrise Converters','WestEdge Printworks','Orbit Packaging','Sterling Papers','Nova Corrugation','Evergreen Boards','FinePack Industries','Maruti Converters','BluePeak Packaging','National Print House','Pioneer Cartons','Crystal Packworks','Vertex Labels','Shakti Paper Traders','SilverLine Industries','Trident Packaging','Omkar Paper Products','Royal Corrugators','Unity Print & Pack','Kaveri Distributors','Pragati Enterprises','Zenith Packaging'];
  const cities=['Pune','Mumbai','Nashik','Nagpur','Ahmedabad','Vadodara','Indore','Bengaluru','Hyderabad','Surat'];
  names.forEach((name,i)=>db.customers.push({
    id:`C${String(i+6).padStart(3,'0')}`,code:`CUST-${String(1006+i)}`,name,
    gst:`27AAB${String.fromCharCode(67+i%20)}${String(1000+i).padStart(4,'0')}A1Z${(i%8)+1}`,
    city:cities[i%cities.length],terms:[30,45,60][i%3]+' Days',owner:['Rahul Mehta','Neha Shah','Arjun Rao'][i%3],status:i%11===0?'On Hold':'Active',outstanding:Math.round((120000+i*43120)/100)*100
  }));
  const reqs=['Kraft Paper','Writing Paper','Duplex Board','Industrial Paper','Coated Paper','Light Kraft','Folding Box Board','Tissue Base'];
  for(let i=0;i<40;i++){
    const cid=db.customers[i%db.customers.length].id, p=db.products[i%db.products.length];
    db.enquiries.push({id:`ENQ-2026-${String(124+i).padStart(5,'0')}`,customerId:cid,date:`2026-09-${String((i%22)+1).padStart(2,'0')}`,requirement:`${(4+i%18)+1} MT ${reqs[i%reqs.length]}, ${p.gsm} GSM, ${p.size} ${p.form}`,status:['New','Quoted','Quoted','Converted'][i%4],owner:['Rahul Mehta','Neha Shah','Arjun Rao'][i%3]});
  }
  for(let i=0;i<35;i++){
    const e=db.enquiries[i], value=Math.round((220000+i*29500)/100)*100;
    db.quotations.push({id:`QT-2026-${String(452+i).padStart(5,'0')}`,enquiry:e.id,customerId:e.customerId,date:e.date,validity:'2026-10-15',total:value,status:['Draft','Sent','Accepted'][i%3],owner:e.owner});
  }
  const plants=['Pune Plant','Mumbai Plant','Nagpur Plant','Bengaluru Plant','Ahmedabad Plant'];
  const orderStates=['Approved','Approved','In Production','Approval','Ready for Dispatch','Dispatched','Delivered','Draft'];
  for(let i=0;i<30;i++){
    const cid=db.customers[i%db.customers.length].id, p=db.products[i%db.products.length], qty=3+(i%15), rate=p.rate-(i%4)*750;
    const subtotal=qty*rate, discount=i%5===0?5000:0, tax=Math.round((subtotal-discount)*.18), freight=qty*1200, total=subtotal-discount+tax+freight;
    const state=orderStates[i%orderStates.length];
    const approved=['Approved','In Production','Ready for Dispatch','Dispatched','Delivered'].includes(state);
    const order={id:`SO-2026-${String(10452+i).padStart(5,'0')}`,sapNo:i%2===0?`0000${10000+i}`:'',source:i%2===0?'SAP':'PORTAL',customerId:cid,customerPO:`PO/${2026}/${String(300+i).padStart(4,'0')}`,orderDate:`2026-09-${String((i%22)+1).padStart(2,'0')}`,deliveryDate:`2026-10-${String((i%20)+1).padStart(2,'0')}`,plant:plants[i%plants.length],subtotal,discount,tax,freight,total,orderStatus:state,approvalStatus:approved?'APPROVED':state==='Approval'?`STAGE_${(i%3)+1}_PENDING`:'DRAFT',currentStage:state==='Approval'?(i%3)+1:null,syncStatus:i%2===0?'SYNCED':'NOT_SYNCED',createdBy:i%2===0?'SAB':['Rahul Mehta','Neha Shah','Arjun Rao'][i%3],items:[{productId:p.id,qty,rate,discount,tax:18}]};
    db.orders.push(order);
    if(order.approvalStatus==='APPROVED'){
      for(let s=1;s<=3;s++) db.approvals.push({id:`AP-${i}-${s}`,orderId:order.id,stage:s,role:['','Sales Manager','Production','Management'][s],status:'APPROVED',user:['','SAB','Rakesh','Anita'][s],date:order.orderDate,time:['','09:15:22','10:08:14','12:34:11'][s],comments:['','Commercial terms verified.','Technical feasibility confirmed.','Final authorization granted.'][s]});
    } else if(order.currentStage){
      for(let s=1;s<order.currentStage;s++) db.approvals.push({id:`AP-${i}-${s}`,orderId:order.id,stage:s,role:['','Sales Manager','Production','Management'][s],status:'APPROVED',user:['','SAB','Rakesh','Anita'][s],date:order.orderDate,time:'09:20:00',comments:'Approved.'});
      db.approvals.push({id:`AP-${i}-${order.currentStage}`,orderId:order.id,stage:order.currentStage,role:['','Sales Manager','Production','Management'][order.currentStage],status:'PENDING',user:'',date:'',time:'',comments:''});
    }
    db.audit.push({id:`LOG-${i}`,orderId:order.id,action:'Order Imported / Created',user:order.createdBy,time:`${order.orderDate} 09:00:00`});
  }
  for(let i=0;i<10;i++){
    const p=db.products[i%db.products.length]; db.inventory.push({productId:p.id,plant:plants[i%plants.length],onHand:30+i*4,reserved:8+i%10,available:22+i*2});
  }
  const prodStates=['Planned','Raw Material Allocated','Scheduled','In Production','Quality Inspection','Ready for Dispatch'];
  for(let i=0;i<18;i++){
    const order=db.orders[i%db.orders.length], item=order.items[0], p=db.products.find(x=>x.id===item.productId) || db.products[0], progress=[5,18,30,62,82,100][i%6], produced=Math.round(item.qty*progress/100*10)/10;
    const status=prodStates[i%6];
    db.production.push({id:`PR-26${String(100+i).padStart(3,'0')}`,orderId:order.id,productId:p.id,qty:item.qty,produced,pending:Math.max(0,item.qty-produced),plant:order.plant,planned:'2026-09-'+String(23+(i%7)).padStart(2,'0'),eta:'2026-09-'+String(26+(i%7)).padStart(2,'0'),status,progress,machine:['PM-01','PM-02','PM-03','PM-04'][i%4],shift:['A','B','C'][i%3],operator:['Rakesh','Vijay','Sameer','Kiran'][i%4],rawMaterial:i%6===0?'Awaiting pulp allocation':'Allocated',blocker:i%7===0?'Awaiting raw-material release':'None',lastUpdate:`2026-09-${String(20+(i%3)).padStart(2,'0')} ${10+(i%8)}:15:00`,timeline:[
      {stage:'Order Released',status:'Done',time:'09:10'},
      {stage:'Raw Material Allocated',status:i%6===0?'Pending':'Done',time:'09:45'},
      {stage:'Production Scheduled',status:i%1===0?'Done':'Pending',time:'11:20'},
      {stage:'In Production',status:['In Production','Quality Inspection','Ready for Dispatch'].includes(status)?'In Progress':'Pending',time:'13:30'},
      {stage:'Quality Inspection',status:status==='Quality Inspection'||status==='Ready for Dispatch'?'Pending':'Queued',time:'—'},
      {stage:'Ready for Dispatch',status:status==='Ready for Dispatch'?'Pending':'Queued',time:'—'}
    ]});
  }
  for(let i=0;i<18;i++){
    const order=db.orders[(i+5)%db.orders.length], p=db.products.find(x=>x.id===order.items[0].productId) || db.products[0], result=i%4===0?'Pending':'Passed';
    db.quality.push({id:`QC-${String(i+1).padStart(3,'0')}`,orderId:order.id,gsm:p.gsm,grade:p.grade,size:p.size,result,reviewer:result==='Passed'?'Rakesh':'',date:result==='Passed'?order.orderDate:''});
    if(i<12) db.dispatches.push({id:`DSP-26${String(81+i).padStart(2,'0')}`,orderId:order.id,customerId:order.customerId,qty:Math.max(1,Math.round(order.items[0].qty/2)),vehicle:`MH-${10+i%5}-AB-${1000+i}`,transporter:['Swift Logistics','BlueLine Transport','GreenLine Logistics'][i%3],date:'2026-09-'+String(22+(i%5)).padStart(2,'0'),status:['Ready','Dispatched','In Transit','Delivered'][i%4]});
  }
  for(let i=0;i<12;i++){
    const order=db.orders[(i+3)%db.orders.length], total=order.total, delivered=i%3===0?order.items[0].qty/2:order.items[0].qty;
    db.deliveries.push({id:`DEL-26${String(31+i).padStart(3,'0')}`,orderId:order.id,customerId:order.customerId,delivered, pending:Math.max(0,order.items[0].qty-delivered),date:'2026-09-'+String(22+(i%6)).padStart(2,'0'),status:delivered<order.items[0].qty?'Partially Delivered':'Delivered',pod:`POD-${order.id.slice(-5)}-${i+1}.pdf`});
    db.invoices.push({id:`INV-${50021+i}`,invoiceNo:`INV/26-27/${50021+i}`,orderId:order.id,customerId:order.customerId,amount:total,due:'2026-10-'+String(20+(i%8)).padStart(2,'0'),paid:i%3===0?Math.round(total*.5):i%3===1?total:0,status:i%3===0?'Partially Paid':i%3===1?'Paid':'Overdue'});
  }
  db.invoices.forEach((inv,i)=>{ if(inv.paid){ db.payments.push({id:`PAY-${90011+i}`,invoiceId:inv.id,amount:inv.paid,date:'2026-09-23',mode:i%2?'RTGS':'NEFT',reference:`BANK/${9000+i}`}); }});
  return db;
}

function loadDB(){
  try{
    const saved=JSON.parse(localStorage.getItem(DB_KEY));
    if(saved && saved.version===3) return saved;
  }catch{}
  const db=makeBigCompanyData(deepClone(seed)); db.version=3; localStorage.setItem(DB_KEY,JSON.stringify(db)); return db;
}
APP.db=loadDB();
function saveDB(){localStorage.setItem(DB_KEY,JSON.stringify(APP.db));}

function requireAuth(){ return !!APP.state.user; }
function go(route){ location.hash=route; }
window.addEventListener('hashchange',()=>{APP.state.route=location.hash.replace('#','')||'dashboard';render();});

function loginPage(){
  return `<div class="auth-shell"><div class="auth-card">
    <div class="brand-row"><div class="brand-mark">G</div><div><div class="brand-title dark">GreenPaper</div><div class="brand-sub dark-sub">Sales Order Management</div></div></div>
    <div class="auth-title">Welcome back</div><div class="auth-sub">Sign in with an account created in this demo.</div>
    <form onsubmit="login(event)">
      <div class="field"><label>Email</label><input name="email" type="email" required placeholder="name@company.com" autocomplete="username"/></div>
      <div class="field"><label>Password</label><input name="password" type="password" required placeholder="••••••••" autocomplete="current-password"/></div>
      <button class="btn primary auth-btn">Log in</button>
    </form>
    <div class="auth-footer">New team member? <a href="#signup">Create account</a></div>
    <div class="auth-note">Only signed-up users can access this demo. Choose one of the three business profiles during signup.</div>
  </div></div>`;
}
function signupPage(){
  return `<div class="auth-shell"><div class="auth-card">
    <div class="brand-row"><div class="brand-mark">G</div><div><div class="brand-title dark">GreenPaper</div><div class="brand-sub dark-sub">Sales Order Management</div></div></div>
    <div class="auth-title">Create your account</div><div class="auth-sub">Create a demo profile for your role. You must sign up before logging in.</div>
    <form onsubmit="signup(event)">
      <div class="form-grid"><div class="field"><label>Full Name</label><input name="name" required placeholder="e.g. Anita Sharma"/></div>
      <div class="field"><label>Role</label><select name="role" required>${ROLES.map(r=>`<option>${r}</option>`).join('')}</select></div>
      <div class="field"><label>Email</label><input name="email" type="email" required placeholder="name@company.com"/></div>
      <div class="field"><label>Password</label><input name="password" type="password" minlength="6" required placeholder="Minimum 6 characters"/></div></div>
      <button class="btn primary auth-btn">Create account</button>
    </form>
    <div class="auth-footer">Already registered? <a href="#login">Back to login</a></div>
  </div></div>`;
}

function navItem(route,label){return `<a class="nav-item ${APP.state.route===route?'active':''}" href="#${route}"><span class="nav-icon">${APP.icons[route]||'•'}</span><span>${label}</span></a>`;}
function layout(content){
  const user=APP.state.user;
  return `<div class="app-shell"><aside class="sidebar">
    <div class="brand"><div class="brand-row"><div class="brand-mark">G</div><div><div class="brand-title">GreenPaper</div><div class="brand-sub">Sales Order Management</div></div></div></div>
    <nav class="nav">
      <div class="nav-section">General</div>${navItem('dashboard','Dashboard')}
      <div class="nav-section">Sales</div>${navItem('customers','Customers')}${navItem('enquiries','Enquiries')}${navItem('quotations','Quotations')}${navItem('orders','Sales Orders')}
      <div class="nav-section">Approvals</div>${navItem('approvals','Approval Inbox')}
      <div class="nav-section">Operations</div>${navItem('inventory','Inventory')}${navItem('production','Production')}${navItem('quality','Quality / Technical')}${navItem('dispatch','Dispatch')}${navItem('delivery','Delivery')}
      <div class="nav-section">Finance</div>${navItem('invoices','Invoices')}${navItem('payments','Payments')}
      <div class="nav-section">Analytics</div>${navItem('reports','Reports')}
      <div class="nav-section">Account</div>${navItem('profile','Profile')}${navItem('settings','Settings')}
    </nav>
    <div class="sidebar-foot"><div class="status-dot">●</div> SAP ${sapStatusLabel()} • auto-sync 15 min</div>
  </aside><main class="main"><header class="topbar"><div class="page-title">${pageTitle()}</div><div class="top-spacer"></div><input class="search" placeholder="Search orders, customers…" value="${escapeHtml(APP.state.search)}" oninput="APP.state.search=this.value;render()"/><button class="user-pill" onclick="go('profile')"><div class="avatar">${initials(user.name)}</div><div class="user-pill-copy"><b>${escapeHtml(user.name)}</b><span>${escapeHtml(user.role)}</span></div></button></header><section class="content">${content}</section></main></div><div id="modal-root"></div><div id="drawer-root"></div>`;
}
function initials(name){return String(name||'U').split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase();}
function pageTitle(){const r=APP.state.route;return r==='orders'?'Sales Orders':r==='quality'?'Quality / Technical':r.charAt(0).toUpperCase()+r.slice(1);}

function render(){
  if(!requireAuth() && !['login','signup'].includes(APP.state.route)){go('login');return;}
  if(!requireAuth()){
    document.getElementById('app').innerHTML=APP.state.route==='signup'?signupPage():loginPage(); return;
  }
  let content=''; switch(APP.state.route){
    case 'dashboard':content=dashboardPage();break;case 'customers':content=customersPage();break;case 'enquiries':content=enquiriesPage();break;case 'quotations':content=quotationsPage();break;case 'orders':content=ordersPage();break;case 'approvals':content=approvalsPage();break;case 'inventory':content=inventoryPage();break;case 'production':content=productionPage();break;case 'quality':content=qualityPage();break;case 'dispatch':content=dispatchPage();break;case 'delivery':content=deliveryPage();break;case 'invoices':content=invoicesPage();break;case 'payments':content=paymentsPage();break;case 'reports':content=reportsPage();break;case 'profile':content=profilePage();break;case 'settings':content=settingsPage();break;default:content=dashboardPage();
  }
  document.getElementById('app').innerHTML=layout(content);
}

function pageHead(title,sub,actions=''){return `<div class="page-head"><div><h1>${title}</h1><p>${sub}</p></div><div class="actions">${actions}</div></div>`;}
function kpi(label,value,meta,icon){return `<div class="card kpi"><div class="kpi-top"><div class="kpi-label">${label}</div><div class="kpi-icon">${icon}</div></div><div class="kpi-value">${value}</div><div class="kpi-meta">${meta}</div></div>`;}

function dashboardPage(){
  const sales=APP.db.orders.reduce((a,o)=>a+o.total,0), open=APP.db.orders.filter(o=>!['Delivered','Completed','Closed'].includes(o.orderStatus)).length, pending=APP.db.orders.filter(o=>o.approvalStatus.includes('PENDING')).length, receivable=APP.db.invoices.reduce((a,x)=>a+x.amount-x.paid,0);
  const recent=APP.db.orders.slice(-7).reverse();
  const prodIssues=APP.db.production.filter(p=>p.blocker && p.blocker!=='None').slice(0,4);
  return pageHead('Dashboard','Live SAP synchronized view of sales, approval, production and activity.',`<button class="btn" onclick="syncSAP()">↻ Sync SAP</button><button class="btn primary" data-modal="create-order">+ Create Sales Order</button>`)+
  `<div class="grid grid-4">${kpi('Total Order Value',money(sales),'30+ active demo orders','↗')}${kpi('Open Sales Orders',open,'Across all plants','▣')}${kpi('Pending Approvals',pending,'3-stage workflow','✓')}${kpi('Outstanding',money(receivable),'Receivables view','₹')}</div>
  <div style="height:16px"></div><div class="grid grid-3"><div class="card pad" style="grid-column:span 2"><div class="section-title">Sales Trend</div><div class="section-sub">Rolling 12 months • ₹ Lakhs</div><div class="chart">${[42,54,46,62,58,72,65,82,76,94,89,100].map((v,i)=>`<div class="bar"><div class="bar-value">${12+i*3}</div><div class="bar-fill" style="height:${v*1.4}px"></div><div class="bar-label">${['Oct','Nov','Dec','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep'][i]}</div></div>`).join('')}</div></div><div class="card pad"><div class="section-title">Approval Pipeline</div><div class="list">${[['Sales Manager',APP.db.orders.filter(o=>o.currentStage===1).length],['Production',APP.db.orders.filter(o=>o.currentStage===2).length],['Management',APP.db.orders.filter(o=>o.currentStage===3).length]].map(x=>`<div class="list-row"><div class="list-main"><div class="list-title">${x[0]}</div><div class="list-meta">Pending review</div></div><b>${x[1]}</b></div>`).join('')}</div></div></div>
  <div style="height:16px"></div><div class="grid grid-2"><div class="card"><div class="card-header"><div><div class="section-title" style="margin:0">Recent Sales Orders</div><div class="section-sub" style="margin:3px 0 0">SAP and portal activity</div></div><a class="btn" href="#orders">View all</a></div><div class="table-wrap">${orderTable(recent)}</div></div><div class="card"><div class="card-header"><div><div class="section-title" style="margin:0">Production Visibility</div><div class="section-sub" style="margin:3px 0 0">Current blockers and next milestones</div></div><a class="btn" href="#production">Open production</a></div><div class="list" style="padding:12px 15px">${APP.db.production.slice(0,5).map(p=>`<div class="list-row"><div class="list-main"><div class="list-title">${p.id} • ${product(p.productId).name}</div><div class="list-meta">${p.produced} / ${p.qty} MT • ${p.machine} • ${p.shift} shift</div></div>${statusBadge(p.status)}</div>`).join('')}</div></div></div>
  <div style="height:16px"></div><div class="grid grid-3"><div class="card pad"><div class="section-title">SAP Connection</div><div class="notice"><b>● ${sapStatusLabel()}</b><br>Live SAP • E0003: ${APP.state.sapSync.employeeCounts.E0003||0} orders • E0006: ${APP.state.sapSync.employeeCounts.E0006||0} orders<br>Last sync: ${sapDateTime(APP.state.sapSync.lastSync)}${APP.state.sapSync.error?`<br><span class="subtle">${escapeHtml(APP.state.sapSync.error)}</span>`:''}</div></div><div class="card pad"><div class="section-title">Production Alerts</div><div class="list">${prodIssues.map(p=>`<div class="list-row"><div class="list-main"><div class="list-title">${p.id}</div><div class="list-meta">${escapeHtml(p.blocker)}</div></div>${statusBadge('Delayed')}</div>`).join('')||'<div class="empty">No active blockers</div>'}</div></div><div class="card pad"><div class="section-title">Upcoming Deliveries</div><div class="list">${APP.db.deliveries.slice(0,4).map(d=>`<div class="list-row"><div class="list-main"><div class="list-title">${d.orderId}</div><div class="list-meta">${customer(d.customerId).name} • ${fmtDate(d.date)}</div></div>${statusBadge(d.status)}</div>`).join('')}</div></div></div>`;
}
function orderTable(rows){return `<table class="table"><thead><tr><th>SO Number</th><th>Customer</th><th>Source</th><th>Value</th><th>Approval</th><th>Status</th><th>Action</th></tr></thead><tbody>${rows.map(o=>`<tr><td><b>${o.id}</b>${o.sapNo?`<div class="subtle">SAP ${o.sapNo}</div>`:''}</td><td>${customer(o.customerId).name}</td><td>${o.source==='SAP'?'<span class="badge blue">SAP</span>':'<span class="badge gray">PORTAL</span>'}</td><td>${money(o.total)}</td><td>${statusBadge(o.approvalStatus)}</td><td>${statusBadge(o.orderStatus)}</td><td><button class="btn" data-drawer="order" data-id="${o.id}">View</button></td></tr>`).join('')}</tbody></table>`;}

function customersPage(){const q=APP.state.search.toLowerCase();const rows=APP.db.customers.filter(c=>`${c.name} ${c.code} ${c.city}`.toLowerCase().includes(q));return pageHead('Customers','Large-company customer master and receivable visibility.',`<button class="btn primary" data-modal="customer-form">+ Add Customer</button>`)+`<div class="card pad"><div class="filters"><input class="filter" placeholder="Search customer…" value="${escapeHtml(APP.state.search)}" oninput="APP.state.search=this.value;render()"/><select class="filter"><option>All regions</option><option>West</option><option>South</option><option>Central</option></select><select class="filter"><option>All status</option><option>Active</option><option>On Hold</option></select></div><div class="table-wrap"><table class="table"><thead><tr><th>Customer</th><th>GST</th><th>City</th><th>Terms</th><th>Owner</th><th>Outstanding</th><th>Status</th><th></th></tr></thead><tbody>${rows.map(c=>`<tr><td><b>${c.name}</b><div class="subtle">${c.code}</div></td><td>${c.gst}</td><td>${c.city}</td><td>${c.terms}</td><td>${c.owner}</td><td>${money(c.outstanding)}</td><td>${statusBadge(c.status)}</td><td><button class="btn" data-modal="customer-detail" data-id="${c.id}">View</button></td></tr>`).join('')}</tbody></table></div></div>`;}
function enquiriesPage(){const q=APP.state.search.toLowerCase();const rows=APP.db.enquiries.filter(e=>(`${e.id} ${customer(e.customerId).name} ${e.requirement}`).toLowerCase().includes(q));return pageHead('Enquiries','High-volume enquiry pipeline for a large paper business.',`<button class="btn primary" data-modal="enquiry-form">+ New Enquiry</button>`)+`<div class="card pad"><div class="filters"><input class="filter" placeholder="Search enquiry/customer…" value="${escapeHtml(APP.state.search)}" oninput="APP.state.search=this.value;render()"/><select class="filter"><option>All status</option><option>New</option><option>Quoted</option><option>Converted</option></select></div><div class="table-wrap"><table class="table"><thead><tr><th>Enquiry</th><th>Date</th><th>Customer</th><th>Requirement</th><th>Owner</th><th>Status</th><th></th></tr></thead><tbody>${rows.map(e=>`<tr><td><b>${e.id}</b></td><td>${fmtDate(e.date)}</td><td>${customer(e.customerId).name}</td><td>${e.requirement}</td><td>${e.owner}</td><td>${statusBadge(e.status)}</td><td><button class="btn" data-modal="enquiry-detail" data-id="${e.id}">View</button></td></tr>`).join('')}</tbody></table></div></div>`;}
function quotationsPage(){return pageHead('Quotations','Commercial offers, validity and conversion to sales orders.',`<button class="btn primary" data-modal="quotation-form">+ New Quotation</button>`)+`<div class="card pad"><div class="filters"><input class="filter" placeholder="Search quotation/customer…" oninput="APP.state.search=this.value;render()"/><select class="filter"><option>All status</option><option>Draft</option><option>Sent</option><option>Accepted</option></select></div><div class="table-wrap"><table class="table"><thead><tr><th>Quotation</th><th>Enquiry</th><th>Customer</th><th>Date</th><th>Validity</th><th>Total</th><th>Status</th><th></th></tr></thead><tbody>${APP.db.quotations.filter(q=>(`${q.id} ${customer(q.customerId).name}`).toLowerCase().includes(APP.state.search.toLowerCase())).map(q=>`<tr><td><b>${q.id}</b></td><td>${q.enquiry}</td><td>${customer(q.customerId).name}</td><td>${fmtDate(q.date)}</td><td>${fmtDate(q.validity)}</td><td>${money(q.total)}</td><td>${statusBadge(q.status)}</td><td><button class="btn" data-modal="quotation-detail" data-id="${q.id}">View</button></td></tr>`).join('')}</tbody></table></div></div>`;}
function ordersPage(){let rows=APP.db.orders;const q=APP.state.search.toLowerCase();if(q) rows=rows.filter(o=>`${o.id} ${o.sapNo} ${customer(o.customerId).name} ${o.customerPO}`.toLowerCase().includes(q));const tab=APP.state.filters.orderTab||'All';if(tab==='SAP Orders')rows=rows.filter(o=>o.source==='SAP');if(tab==='Portal Orders')rows=rows.filter(o=>o.source==='PORTAL');if(tab==='Pending Approval')rows=rows.filter(o=>o.approvalStatus.includes('PENDING'));if(tab==='Approved')rows=rows.filter(o=>o.approvalStatus==='APPROVED');if(tab==='In Production')rows=rows.filter(o=>o.orderStatus==='In Production');if(tab==='Dispatched')rows=rows.filter(o=>o.orderStatus==='Dispatched');if(tab==='Delivered')rows=rows.filter(o=>o.orderStatus==='Delivered');return pageHead('Sales Orders','Live SAP-originated orders plus portal orders. SAP refreshes automatically every 15 minutes.',`<button class="btn" onclick="syncSAP()">↻ Sync SAP</button><button class="btn primary" data-modal="create-order">+ Create Sales Order</button>`)+`<div class="card"><div class="card-header"><div class="actions">${['All','SAP Orders','Portal Orders','Pending Approval','Approved','In Production','Dispatched','Delivered'].map(t=>`<button class="btn ${tab===t?'primary':''}" onclick="APP.state.filters.orderTab='${t}';render()">${t}</button>`).join('')}</div></div><div class="card-header"><div class="filters" style="margin:0"><input class="filter" placeholder="Search order / customer / PO…" value="${escapeHtml(APP.state.search)}" oninput="APP.state.search=this.value;render()"/><select class="filter"><option>All Plants</option>${['Pune Plant','Mumbai Plant','Nagpur Plant','Bengaluru Plant','Ahmedabad Plant'].map(x=>`<option>${x}</option>`).join('')}</select></div></div><div class="table-wrap">${orderTable(rows)}</div></div>`;}

function approvalsPage(){const pending=APP.db.orders.filter(o=>o.approvalStatus.includes('PENDING'));const currentRole=APP.state.user.role;const stageMap={'Sales Manager':1,'Production':2,'Management':3};return pageHead('Approval Inbox','Three-stage sequential approval. Only the current profile can approve its stage.',`<button class="btn" onclick="resetDemo()">Reset Demo Data</button>`)+`<div class="notice" style="margin-bottom:16px"><b>Stages:</b> Sales Manager → Production → Management. Finance is not part of the approval workflow.</div><div class="grid grid-3">${[['Stage 1','Sales Manager',1],['Stage 2','Production',2],['Stage 3','Management',3]].map(x=>`<div class="card pad"><div class="section-title">${x[0]}</div><div style="font-size:24px;font-weight:800">${pending.filter(o=>o.currentStage===x[2]).length}</div><div class="subtle">${x[1]}</div></div>`).join('')}</div><div style="height:16px"></div><div class="card"><div class="card-header"><div><div class="section-title" style="margin:0">Orders awaiting approval</div><div class="section-sub" style="margin:3px 0 0">Current profile: ${currentRole}</div></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Order</th><th>Customer</th><th>Value</th><th>Stage</th><th>Owner</th><th>Action</th></tr></thead><tbody>${pending.map(o=>`<tr><td><b>${o.id}</b></td><td>${customer(o.customerId).name}</td><td>${money(o.total)}</td><td>${statusBadge(`STAGE_${o.currentStage}_PENDING`)}</td><td>${o.createdBy}</td><td><button class="btn primary" data-modal="approval-detail" data-id="${o.id}">Review</button></td></tr>`).join('')||'<tr><td colspan="6"><div class="empty">No pending approvals</div></td></tr>'}</tbody></table></div></div>`;}

function productionPage(){return pageHead('Production','Transparent production control from order release to ready-for-dispatch.',`<button class="btn primary" data-modal="production-form">+ Production Request</button>`)+`<div class="grid grid-4">${kpi('Active Jobs',APP.db.production.filter(p=>p.status!=='Ready for Dispatch').length,'Across plants','⚙')}${kpi('In Production',APP.db.production.filter(p=>p.status==='In Production').length,'Running now','▶')}${kpi('Quality Checks',APP.db.production.filter(p=>p.status==='Quality Inspection').length,'Awaiting inspection','◍')}${kpi('Blocked Jobs',APP.db.production.filter(p=>p.blocker && p.blocker!=='None').length,'Need attention','!')}</div><div style="height:16px"></div><div class="card"><div class="card-header"><div><div class="section-title" style="margin:0">Production Control Board</div><div class="section-sub" style="margin:3px 0 0">Open a job to see live stage-by-stage transparency.</div></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Production</th><th>Sales Order</th><th>Product</th><th>Qty</th><th>Produced</th><th>Progress</th><th>Machine</th><th>ETA</th><th>Status</th><th>Action</th></tr></thead><tbody>${APP.db.production.map(p=>`<tr><td><b>${p.id}</b></td><td>${p.orderId}</td><td>${product(p.productId).name}</td><td>${p.qty} MT</td><td>${p.produced} MT</td><td><div style="min-width:120px"><div class="progress"><span style="width:${p.progress}%"></span></div><div class="subtle" style="font-size:9px;margin-top:3px">${p.progress}%</div></div></td><td>${p.machine}<div class="subtle">Shift ${p.shift}</div></td><td>${fmtDate(p.eta)}</td><td>${statusBadge(p.status)}</td><td><button class="btn" data-drawer="production" data-id="${p.id}">Track</button></td></tr>`).join('')}</tbody></table></div></div>`;}
function qualityPage(){return pageHead('Quality / Technical','Paper specification checks linked to production and sales orders.',`<button class="btn primary" data-modal="quality-form">+ Technical Check</button>`)+`<div class="card pad"><div class="table-wrap"><table class="table"><thead><tr><th>Check</th><th>Sales Order</th><th>GSM</th><th>Grade</th><th>Size</th><th>Reviewer</th><th>Result</th><th></th></tr></thead><tbody>${APP.db.quality.map(q=>`<tr><td><b>${q.id}</b></td><td>${q.orderId}</td><td>${q.gsm}</td><td>${q.grade}</td><td>${q.size}</td><td>${q.reviewer||'—'}</td><td>${statusBadge(q.result)}</td><td><button class="btn" onclick="setQuality('${q.id}')">${q.result==='Passed'?'View':'Review'}</button></td></tr>`).join('')}</tbody></table></div></div>`;}
function inventoryPage(){return pageHead('Inventory','On-hand, reserved and available stock across multiple plants.',`<button class="btn" onclick="toast('Inventory refreshed from mock SAP')">↻ Refresh</button>`)+`<div class="card pad"><div class="filters"><input class="filter" placeholder="Search product / plant…" value="${escapeHtml(APP.state.search)}" oninput="APP.state.search=this.value;render()"/></div><div class="table-wrap"><table class="table"><thead><tr><th>Product</th><th>Grade</th><th>GSM</th><th>Plant</th><th>On Hand</th><th>Reserved</th><th>Available</th><th>Status</th></tr></thead><tbody>${APP.db.inventory.filter(i=>(product(i.productId).name+' '+i.plant).toLowerCase().includes(APP.state.search.toLowerCase())).map(i=>{const p=product(i.productId);return `<tr><td><b>${p.name}</b><div class="subtle">${p.code}</div></td><td>${p.grade}</td><td>${p.gsm}</td><td>${i.plant}</td><td>${i.onHand} MT</td><td>${i.reserved} MT</td><td>${i.available} MT</td><td>${statusBadge(i.available>0?'Available':'Shortage')}</td></tr>`}).join('')}</tbody></table></div></div>`;}
function dispatchPage(){return pageHead('Dispatch','Transport assignment and dispatch lifecycle.',`<button class="btn primary" data-modal="dispatch-form">+ Dispatch</button>`)+`<div class="card pad"><div class="table-wrap"><table class="table"><thead><tr><th>Dispatch</th><th>Sales Order</th><th>Customer</th><th>Qty</th><th>Vehicle</th><th>Transporter</th><th>Date</th><th>Status</th><th></th></tr></thead><tbody>${APP.db.dispatches.map(d=>`<tr><td><b>${d.id}</b></td><td>${d.orderId}</td><td>${customer(d.customerId).name}</td><td>${d.qty} MT</td><td>${d.vehicle}</td><td>${d.transporter}</td><td>${fmtDate(d.date)}</td><td>${statusBadge(d.status)}</td><td><button class="btn" onclick="advanceDispatch('${d.id}')">Advance</button></td></tr>`).join('')}</tbody></table></div></div>`;}
function deliveryPage(){return pageHead('Delivery','Track delivered versus remaining quantity and POD.',`<button class="btn primary" data-modal="delivery-form">+ Record Delivery</button>`)+`<div class="card pad"><div class="table-wrap"><table class="table"><thead><tr><th>Delivery</th><th>Sales Order</th><th>Customer</th><th>Delivered</th><th>Pending</th><th>Date</th><th>Status</th><th>POD</th></tr></thead><tbody>${APP.db.deliveries.map(d=>`<tr><td><b>${d.id}</b></td><td>${d.orderId}</td><td>${customer(d.customerId).name}</td><td>${d.delivered} MT</td><td>${d.pending} MT</td><td>${fmtDate(d.date)}</td><td>${statusBadge(d.status)}</td><td><button class="btn" onclick="toast('Opening ${d.pod} in demo viewer')">View POD</button></td></tr>`).join('')}</tbody></table></div></div>`;}
function invoicesPage(){const invoiced=APP.db.invoices.reduce((a,x)=>a+x.amount,0),paid=APP.db.invoices.reduce((a,x)=>a+x.paid,0);return pageHead('Invoices','Invoice status and receivable visibility for the business.',`<button class="btn primary" data-modal="invoice-form">+ Generate Invoice</button>`)+`<div class="grid grid-3">${kpi('Invoiced',money(invoiced),`${APP.db.invoices.length} invoices`,'₹')}${kpi('Collected',money(paid),'Paid + partial','₹')}${kpi('Outstanding',money(invoiced-paid),'Receivable','!')}</div><div style="height:16px"></div><div class="card pad"><div class="table-wrap"><table class="table"><thead><tr><th>Invoice</th><th>Sales Order</th><th>Customer</th><th>Amount</th><th>Due</th><th>Paid</th><th>Outstanding</th><th>Status</th></tr></thead><tbody>${APP.db.invoices.map(i=>`<tr><td><b>${i.invoiceNo}</b><div class="subtle">${i.id}</div></td><td>${i.orderId}</td><td>${customer(i.customerId).name}</td><td>${money(i.amount)}</td><td>${fmtDate(i.due)}</td><td>${money(i.paid)}</td><td>${money(i.amount-i.paid)}</td><td>${statusBadge(i.status)}</td></tr>`).join('')}</tbody></table></div></div>`;}
function paymentsPage(){return pageHead('Payments','Receipt register and payment references.',`<button class="btn primary" data-modal="payment-form">+ Record Payment</button>`)+`<div class="card pad"><div class="table-wrap"><table class="table"><thead><tr><th>Payment</th><th>Invoice</th><th>Amount</th><th>Date</th><th>Mode</th><th>Reference</th></tr></thead><tbody>${APP.db.payments.map(p=>`<tr><td><b>${p.id}</b></td><td>${p.invoiceId}</td><td>${money(p.amount)}</td><td>${fmtDate(p.date)}</td><td>${p.mode}</td><td>${p.reference}</td></tr>`).join('')}</tbody></table></div></div>`;}
function reportsPage(){const total=APP.db.orders.reduce((a,o)=>a+o.total,0), avg=total/Math.max(1,APP.db.orders.length);return pageHead('Reports & Analytics','Sales, approvals, production and fulfilment performance.',`<button class="btn" onclick="exportCSV()">Export CSV</button>`)+`<div class="grid grid-4">${kpi('Order Value',money(total),'All demo orders','↗')}${kpi('Average Order',money(avg),'Per sales order','₹')}${kpi('Approval Ageing','1.8 days','Pending reviews','◷')}${kpi('On-time Delivery','94%','Rolling demo KPI','✓')}</div><div style="height:16px"></div><div class="grid grid-2"><div class="card pad"><div class="section-title">Sales by Customer</div>${APP.db.customers.slice(0,8).map(c=>{const v=APP.db.orders.filter(o=>o.customerId===c.id).reduce((a,o)=>a+o.total,0);return `<div style="margin:11px 0"><div style="display:flex;justify-content:space-between;font-size:11px;margin-bottom:5px"><span>${c.name}</span><b>${money(v)}</b></div><div class="progress"><span style="width:${Math.max(v?8:0,Math.min(100,(v/Math.max(1,total))*480))}%"></span></div></div>`}).join('')}</div><div class="card pad"><div class="section-title">Fulfilment Pipeline</div><div class="list">${[['Approved',APP.db.orders.filter(o=>o.approvalStatus==='APPROVED').length],['In Production',APP.db.orders.filter(o=>o.orderStatus==='In Production').length],['Dispatched',APP.db.orders.filter(o=>o.orderStatus==='Dispatched').length],['Delivered',APP.db.orders.filter(o=>o.orderStatus==='Delivered').length]].map(x=>`<div class="list-row"><div class="list-main"><div class="list-title">${x[0]}</div></div><b>${x[1]}</b></div>`).join('')}</div></div></div><div style="height:16px"></div><div class="card pad"><div class="section-title">Monthly Sales</div><div class="chart">${[26,30,34,42,38,47,44,55,58,62,66,71].map((v,i)=>`<div class="bar"><div class="bar-fill" style="height:${v*2.1}px"></div><div class="bar-label">${['Oct','Nov','Dec','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep'][i]}</div></div>`).join('')}</div></div>`;}
function profilePage(){const u=APP.state.user;return pageHead('Profile','Signed-up member profile and current system role.',`<button class="btn danger" onclick="logout()">Log out</button>`)+`<div class="grid grid-2"><div class="card pad"><div style="display:flex;align-items:center;gap:14px"><div class="profile-avatar">${initials(u.name)}</div><div><div style="font-size:18px;font-weight:800">${escapeHtml(u.name)}</div><div class="subtle">${escapeHtml(u.email)}</div></div></div><div style="height:18px"></div><div class="detail-grid"><div class="detail"><label>Role</label><div>${escapeHtml(u.role)}</div></div><div class="detail"><label>Member Since</label><div>${fmtDate(u.createdAt)}</div></div><div class="detail"><label>Access</label><div>Authenticated</div></div><div class="detail"><label>Approval Stage</label><div>${u.role==='Sales Manager'?'Stage 1':u.role==='Production'?'Stage 2':'Stage 3'}</div></div></div></div><div class="card pad"><div class="section-title">Role responsibility</div>${u.role==='Sales Manager'?'<div class="notice">Owns commercial order review and <b>Stage 1 approval</b>.</div>':u.role==='Production'?'<div class="notice">Owns production/technical review and <b>Stage 2 approval</b>.</div>':'<div class="notice">Owns final management authorization and <b>Stage 3 approval</b>.</div>'}<div style="height:14px"></div><div class="section-title">Demo accounts</div><div class="subtle" style="font-size:11px">To test a different profile, log out and create another signed-up member.</div></div></div>`;}
function settingsPage(){return pageHead('Settings','Live SAP integration configuration and synchronization status.',`<button class="btn primary" onclick="toast('Settings saved for this demo session')">Save</button>`)+`<div class="grid grid-2"><div class="card pad"><div class="section-title">SAP Connection</div><div class="form-grid"><div class="field"><label>Adapter</label><select><option>Live SAP API</option></select></div><div class="field"><label>SAP Client</label><input value="100"/></div><div class="field full"><label>Base URL</label><input value="http://203.112.143.241:8000" readonly/></div><div class="field full"><label>Connection</label><div class="notice"><b>${sapStatusLabel()}</b><br>E0003 orders: ${APP.state.sapSync.employeeCounts.E0003||0}<br>E0006 orders: ${APP.state.sapSync.employeeCounts.E0006||0}<br>Last sync: ${sapDateTime(APP.state.sapSync.lastSync)}<br>Auto-sync interval: 15 minutes</div></div></div></div><div class="card pad"><div class="section-title">Approval Configuration</div><div class="timeline">${ROLES.map((r,i)=>`<div class="step done"><div class="step-dot">${i+1}</div><div class="step-body"><div class="step-title">${r}</div><div class="step-meta">Sequential approval stage ${i+1}</div></div></div>`).join('')}</div></div></div><div style="height:16px"></div><div class="card pad"><div class="section-title">Demo Controls</div><div class="actions"><button class="btn" onclick="resetDemo()">Reset all demo data</button><button class="btn" onclick="syncSAP()">Sync live SAP now</button></div></div>`;}

function openModal(type,id){document.getElementById('modal-root').innerHTML=`<div class="modal-backdrop open" onclick="if(event.target===this)closeModal()"><div class="modal ${['customer-detail','enquiry-detail','quotation-detail'].includes(type)?'small':''}">${modalHTML(type,id)}</div></div>`;}
function closeModal(){const r=document.getElementById('modal-root');if(r)r.innerHTML='';}
function modalHTML(type,id){
  if(type==='create-order') return `<div class="modal-head"><div><b>Create Sales Order</b><div class="subtle">Portal → 3 approvals → SAP</div></div><button class="btn icon-btn" onclick="closeModal()">×</button></div><form id="order-form" onsubmit="createOrder(event)" class="modal-body"><div class="notice">This creates a portal order. Submitting starts Stage 1 with Sales Manager.</div><div style="height:14px"></div><div class="form-grid"><div class="field"><label>Customer *</label><select name="customer" required>${APP.db.customers.slice(0,20).map(c=>`<option value="${c.id}">${c.name}</option>`).join('')}</select></div><div class="field"><label>Customer PO *</label><input name="po" required placeholder="ABC/PO/2026/221"/></div><div class="field"><label>Order Date</label><input name="orderDate" type="date" value="${nowDate()}" required/></div><div class="field"><label>Expected Delivery</label><input name="delivery" type="date" value="2026-10-03" required/></div><div class="field"><label>Plant</label><select name="plant">${['Pune Plant','Mumbai Plant','Nagpur Plant','Bengaluru Plant','Ahmedabad Plant'].map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>Payment Terms</label><select name="terms"><option>30 Days</option><option>45 Days</option><option>60 Days</option></select></div><div class="field"><label>Product *</label><select name="product">${APP.db.products.map(p=>`<option value="${p.id}">${p.name} • ${p.gsm} GSM • ${p.form}</option>`).join('')}</select></div><div class="field"><label>Quantity (MT) *</label><input name="qty" type="number" min="0.1" step="0.1" value="5" required/></div><div class="field"><label>Rate / MT *</label><input name="rate" type="number" min="0" value="${APP.db.products[0].rate}" required/></div><div class="field"><label>Discount</label><input name="discount" type="number" min="0" value="0"/></div><div class="field full"><label>Special Instructions</label><textarea name="notes" placeholder="Customer or production notes"></textarea></div></div><div style="height:14px"></div><div class="card pad"><div class="section-title">Paper specification preview</div><div class="detail-grid"><div class="detail"><label>GSM</label><div>${APP.db.products[0].gsm}</div></div><div class="detail"><label>Grade</label><div>${APP.db.products[0].grade}</div></div><div class="detail"><label>Size / Form</label><div>${APP.db.products[0].size} • ${APP.db.products[0].form}</div></div></div></div></form><div class="modal-foot"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn" onclick="createOrder(null,false)">Save Draft</button><button class="btn primary" onclick="createOrder(null,true)">Submit for Approval</button></div>`;
  if(type==='approval-detail') return approvalModal(id);
  if(type==='customer-form') return formModal('Add Customer',`<form onsubmit="addCustomer(event)"><div class="form-grid"><div class="field"><label>Customer Name</label><input name="name" required/></div><div class="field"><label>GST</label><input name="gst" required/></div><div class="field"><label>City</label><input name="city" required/></div><div class="field"><label>Payment Terms</label><select name="terms"><option>30 Days</option><option>45 Days</option><option>60 Days</option></select></div></div></form>`);
  if(type==='customer-detail'){const c=customer(id);return `<div class="modal-head"><div><b>${c.name}</b><div class="subtle">${c.code}</div></div><button class="btn icon-btn" onclick="closeModal()">×</button></div><div class="modal-body"><div class="detail-grid"><div class="detail"><label>GST</label><div>${c.gst}</div></div><div class="detail"><label>City</label><div>${c.city}</div></div><div class="detail"><label>Terms</label><div>${c.terms}</div></div><div class="detail"><label>Owner</label><div>${c.owner}</div></div><div class="detail"><label>Outstanding</label><div>${money(c.outstanding)}</div></div><div class="detail"><label>Status</label><div>${statusBadge(c.status)}</div></div></div><div style="height:16px"></div><div class="section-title">Orders</div>${orderTable(APP.db.orders.filter(o=>o.customerId===id).slice(0,10))}</div><div class="modal-foot"><button class="btn" onclick="closeModal()">Close</button></div>`;}
  if(type==='enquiry-form') return formModal('New Enquiry',`<form onsubmit="addEnquiry(event)"><div class="form-grid"><div class="field"><label>Customer</label><select name="customer">${APP.db.customers.slice(0,25).map(c=>`<option value="${c.id}">${c.name}</option>`).join('')}</select></div><div class="field"><label>Required Date</label><input name="date" type="date" value="${nowDate()}"/></div><div class="field full"><label>Requirement</label><textarea name="requirement" required placeholder="10 MT Kraft Paper, 120 GSM, 1200 mm Reel"></textarea></div></div></form>`);
  if(type==='enquiry-detail'){const e=APP.db.enquiries.find(x=>x.id===id);return `<div class="modal-head"><div><b>${e.id}</b><div class="subtle">${customer(e.customerId).name}</div></div><button class="btn icon-btn" onclick="closeModal()">×</button></div><div class="modal-body"><div class="detail-grid"><div class="detail"><label>Date</label><div>${fmtDate(e.date)}</div></div><div class="detail"><label>Status</label><div>${statusBadge(e.status)}</div></div><div class="detail"><label>Owner</label><div>${e.owner}</div></div></div><div style="height:14px"></div><div class="notice">${escapeHtml(e.requirement)}</div></div><div class="modal-foot"><button class="btn" onclick="closeModal()">Close</button></div>`;}
  if(type==='quotation-form') return formModal('New Quotation',`<form onsubmit="addQuotation(event)"><div class="form-grid"><div class="field"><label>Enquiry</label><select name="enquiry">${APP.db.enquiries.slice(0,25).map(e=>`<option value="${e.id}">${e.id} • ${customer(e.customerId).name}</option>`).join('')}</select></div><div class="field"><label>Total Value</label><input name="total" type="number" value="600000"/></div><div class="field"><label>Date</label><input name="date" type="date" value="${nowDate()}"/></div><div class="field"><label>Validity</label><input name="validity" type="date" value="2026-10-07"/></div></div></form>`);
  if(type==='quotation-detail'){const q=APP.db.quotations.find(x=>x.id===id);return `<div class="modal-head"><div><b>${q.id}</b><div class="subtle">${customer(q.customerId).name}</div></div><button class="btn icon-btn" onclick="closeModal()">×</button></div><div class="modal-body"><div class="detail-grid"><div class="detail"><label>Status</label><div>${statusBadge(q.status)}</div></div><div class="detail"><label>Total</label><div>${money(q.total)}</div></div><div class="detail"><label>Valid Till</label><div>${fmtDate(q.validity)}</div></div></div></div><div class="modal-foot"><button class="btn" onclick="closeModal()">Close</button><button class="btn primary" onclick="closeModal();openModal('create-order')">Convert to Order</button></div>`;}
  if(type==='production-form') return formModal('Production Request',`<form onsubmit="addProduction(event)"><div class="form-grid"><div class="field"><label>Sales Order</label><select name="order">${APP.db.orders.filter(o=>o.approvalStatus==='APPROVED').slice(0,20).map(o=>`<option>${o.id}</option>`).join('')}</select></div><div class="field"><label>Product</label><select name="product">${APP.db.products.map(p=>`<option value="${p.id}">${p.name}</option>`).join('')}</select></div><div class="field"><label>Quantity (MT)</label><input name="qty" type="number" value="5" step="0.1"/></div><div class="field"><label>Planned Date</label><input name="planned" type="date" value="2026-09-25"/></div><div class="field"><label>Plant</label><select name="plant"><option>Pune Plant</option><option>Mumbai Plant</option><option>Nagpur Plant</option></select></div></div></form>`);
  if(type==='quality-form') return formModal('Technical Check',`<form onsubmit="addQuality(event)"><div class="form-grid"><div class="field"><label>Sales Order</label><select name="order">${APP.db.orders.slice(0,25).map(o=>`<option>${o.id}</option>`).join('')}</select></div><div class="field"><label>GSM</label><input name="gsm" value="120"/></div><div class="field"><label>Grade</label><input name="grade" value="Natural Kraft"/></div><div class="field"><label>Size</label><input name="size" value="1200 mm"/></div><div class="field"><label>Result</label><select name="result"><option>Pending</option><option>Passed</option><option>Failed</option></select></div></div></form>`);
  if(type==='dispatch-form') return formModal('Dispatch',`<form onsubmit="addDispatch(event)"><div class="form-grid"><div class="field"><label>Sales Order</label><select name="order">${APP.db.orders.filter(o=>o.approvalStatus==='APPROVED').slice(0,20).map(o=>`<option>${o.id}</option>`).join('')}</select></div><div class="field"><label>Quantity</label><input name="qty" type="number" step="0.1" value="3"/></div><div class="field"><label>Vehicle</label><input name="vehicle" value="MH-12-AB-1234"/></div><div class="field"><label>Transporter</label><input name="transporter" value="GreenLine Logistics"/></div><div class="field"><label>Dispatch Date</label><input name="date" type="date" value="${nowDate()}"/></div></div></form>`);
  if(type==='delivery-form') return formModal('Record Delivery',`<form onsubmit="addDelivery(event)"><div class="form-grid"><div class="field"><label>Sales Order</label><select name="order">${APP.db.orders.map(o=>`<option>${o.id}</option>`).join('')}</select></div><div class="field"><label>Delivered Quantity</label><input name="qty" type="number" step="0.1" value="3"/></div><div class="field"><label>Date</label><input name="date" type="date" value="${nowDate()}"/></div><div class="field"><label>POD Reference</label><input name="pod" value="POD-DEMO-001.pdf"/></div></div></form>`);
  if(type==='invoice-form') return formModal('Generate Invoice',`<form onsubmit="addInvoice(event)"><div class="form-grid"><div class="field"><label>Sales Order</label><select name="order">${APP.db.orders.map(o=>`<option>${o.id}</option>`).join('')}</select></div><div class="field"><label>Amount</label><input name="amount" type="number" value="500000"/></div><div class="field"><label>Due Date</label><input name="due" type="date" value="2026-10-22"/></div></div></form>`);
  if(type==='payment-form') return formModal('Record Payment',`<form onsubmit="addPayment(event)"><div class="form-grid"><div class="field"><label>Invoice</label><select name="invoice">${APP.db.invoices.map(i=>`<option value="${i.id}">${i.invoiceNo}</option>`).join('')}</select></div><div class="field"><label>Amount</label><input name="amount" type="number" value="100000"/></div><div class="field"><label>Date</label><input name="date" type="date" value="${nowDate()}"/></div><div class="field"><label>Mode</label><select name="mode"><option>NEFT</option><option>RTGS</option><option>Cheque</option></select></div><div class="field full"><label>Reference</label><input name="reference" value="DEMO/PAY/1001"/></div></div></form>`);
  return '';
}
function formModal(title,form){return `<div class="modal-head"><div><b>${title}</b></div><button class="btn icon-btn" onclick="closeModal()">×</button></div><div class="modal-body">${form}</div><div class="modal-foot"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="this.closest('.modal').querySelector('form').requestSubmit()">Save</button></div>`;}
function approvalModal(id){
  const o=APP.db.orders.find(x=>x.id===id), aps=APP.db.approvals.filter(x=>x.orderId===id).sort((a,b)=>a.stage-b.stage), stageMap={'Sales Manager':1,'Production':2,'Management':3}, can=stageMap[APP.state.user.role]===o.currentStage;
  return `<div class="modal-head"><div><b>Approval Review • ${o.id}</b><div class="subtle">${customer(o.customerId).name} • ${money(o.total)}</div></div><button class="btn icon-btn" onclick="closeModal()">×</button></div><div class="modal-body"><div class="detail-grid"><div class="detail"><label>Source</label><div>${o.source}</div></div><div class="detail"><label>Customer PO</label><div>${o.customerPO}</div></div><div class="detail"><label>Delivery</label><div>${fmtDate(o.deliveryDate)}</div></div><div class="detail"><label>Order</label><div>${statusBadge(o.orderStatus)}</div></div><div class="detail"><label>Approval</label><div>${statusBadge(o.approvalStatus)}</div></div><div class="detail"><label>Current Stage</label><div>${o.currentStage||'—'}</div></div></div><div style="height:16px"></div><div class="section-title">Approval Timeline</div><div class="timeline">${[1,2,3].map(s=>{const a=aps.find(x=>x.stage===s);return `<div class="step ${a?.status==='APPROVED'?'done':o.currentStage===s?'current':''}"><div class="step-dot">${a?.status==='APPROVED'?'✓':s}</div><div class="step-body"><div class="step-title">${['','Sales Manager','Production','Management'][s]}</div><div class="step-meta">${a?a.status+(a.user?` • ${a.user}`:'')+(a.date?` • ${fmtDate(a.date)} ${a.time}`:''):o.currentStage===s?'Pending action':'Locked'}</div>${a?.comments?`<div class="subtle" style="font-size:10px">${escapeHtml(a.comments)}</div>`:''}</div></div>`}).join('')}</div>${!can&&o.currentStage?`<div class="notice warning" style="margin-top:14px">Switch to <b>${['','Sales Manager','Production','Management'][o.currentStage]}</b> to action this stage.</div>`:''}</div><div class="modal-foot">${can?`<button class="btn danger" onclick="approvalAction('${id}','REJECTED')">Reject</button><button class="btn" onclick="approvalAction('${id}','SENT BACK')">Send Back</button><button class="btn primary" onclick="approvalAction('${id}','APPROVED')">Approve</button>`:`<button class="btn" onclick="closeModal()">Close</button>`}</div>`;
}

function openDrawer(type,id){
  const root=document.getElementById('drawer-root');if(type==='order'){const o=APP.db.orders.find(x=>x.id===id),c=customer(o.customerId),aps=APP.db.approvals.filter(x=>x.orderId===id).sort((a,b)=>a.stage-b.stage);root.innerHTML=`<div class="drawer open"><div class="drawer-head"><div><b>${o.id}</b><div class="subtle">${c.name}</div></div><button class="btn icon-btn" onclick="closeDrawer()">×</button></div><div class="drawer-body"><div class="actions">${o.source==='SAP'?`<span class="badge blue">SAP ${o.sapNo}</span>`:`<span class="badge gray">PORTAL CREATED</span>`}${statusBadge(o.orderStatus)}${statusBadge(o.approvalStatus)}</div><div style="height:14px"></div><div class="detail-grid"><div class="detail"><label>Customer PO</label><div>${o.customerPO}</div></div><div class="detail"><label>Plant</label><div>${o.plant}</div></div><div class="detail"><label>Delivery</label><div>${fmtDate(o.deliveryDate)}</div></div><div class="detail"><label>Subtotal</label><div>${money(o.subtotal)}</div></div><div class="detail"><label>GST</label><div>${money(o.tax)}</div></div><div class="detail"><label>Total</label><div>${money(o.total)}</div></div></div><div style="height:18px"></div><div class="section-title">Products</div>${o.items.map(i=>{const p=product(i.productId);return `<div class="list-row"><div class="list-main"><div class="list-title">${escapeHtml(i.description||p.name)}</div><div class="list-meta">${i.matnr?`MATNR ${escapeHtml(i.matnr)} • `:''}${i.sapPosnr?`POSNR ${escapeHtml(i.sapPosnr)} • `:''}${i.qty} ${escapeHtml(i.unit||p.unit||'')}</div></div><div><b>${i.qty} ${escapeHtml(i.unit||p.unit||'')}</b><div class="subtle" style="font-size:10px">${money(i.rate)}/${escapeHtml(i.unit||p.unit||'unit')}</div></div></div>`}).join('')}<div style="height:18px"></div><div class="section-title">Approval timeline</div><div class="timeline">${[1,2,3].map(s=>{const a=aps.find(x=>x.stage===s);return `<div class="step ${a?.status==='APPROVED'?'done':o.currentStage===s?'current':''}"><div class="step-dot">${a?.status==='APPROVED'?'✓':s}</div><div class="step-body"><div class="step-title">${['','Sales Manager','Production','Management'][s]}</div><div class="step-meta">${a?a.status+(a.user?` • ${a.user}`:''):'Pending'}</div></div></div>`}).join('')}</div>${o.sapNo?`<div style="height:18px"></div><div class="section-title">SAP information</div><div class="notice">Client: <b>${escapeHtml(o.sapClient||'100')}</b><br>VBELN: <b>${escapeHtml(o.sapNo)}</b><br>SAP user: <b>${escapeHtml(o.sapEmployee||o.createdBy||'—')}</b><br>SAP approval: <b>${escapeHtml(o.sapApprovalStatus||'—')}</b><br>Approval user: <b>${escapeHtml(o.approvalUser||'—')}</b><br>Approval timestamp: <b>${escapeHtml(o.approvalDate||'—')} ${escapeHtml(o.approvalTime||'')}</b><br>Approval code: <b>${escapeHtml(o.sapApprovalCode||'—')}</b><br>Sync: <b>${escapeHtml(o.syncStatus)}</b></div>`:''}</div></div>`;}
  if(type==='production'){const p=APP.db.production.find(x=>x.id===id), o=APP.db.orders.find(x=>x.id===p.orderId), prod=product(p.productId);root.innerHTML=`<div class="drawer open"><div class="drawer-head"><div><b>${p.id}</b><div class="subtle">${prod.name} • ${p.orderId}</div></div><button class="btn icon-btn" onclick="closeDrawer()">×</button></div><div class="drawer-body"><div class="actions">${statusBadge(p.status)}${p.blocker!=='None'?statusBadge('Delayed'):''}<button class="btn primary" onclick="advanceProduction('${p.id}')">Advance Stage</button></div><div style="height:16px"></div><div class="grid grid-2"><div class="card pad"><div class="section-title">Production status</div><div class="detail-grid"><div class="detail"><label>Planned</label><div>${p.qty} MT</div></div><div class="detail"><label>Produced</label><div>${p.produced} MT</div></div><div class="detail"><label>Pending</label><div>${p.pending} MT</div></div><div class="detail"><label>Progress</label><div>${p.progress}%</div></div><div class="detail"><label>Machine</label><div>${p.machine}</div></div><div class="detail"><label>Shift</label><div>${p.shift}</div></div></div></div><div class="card pad"><div class="section-title">Resource & ETA</div><div class="list"><div class="list-row"><div class="list-main"><div class="list-title">Operator</div></div><b>${p.operator}</b></div><div class="list-row"><div class="list-main"><div class="list-title">Raw Material</div></div>${statusBadge(p.rawMaterial)}</div><div class="list-row"><div class="list-main"><div class="list-title">Planned Date</div></div><b>${fmtDate(p.planned)}</b></div><div class="list-row"><div class="list-main"><div class="list-title">Expected Completion</div></div><b>${fmtDate(p.eta)}</b></div></div></div></div><div style="height:16px"></div><div class="card pad"><div class="section-title">Production Progress</div><div class="progress" style="height:12px"><span style="width:${p.progress}%"></span></div><div style="display:flex;justify-content:space-between;font-size:10px;color:var(--muted);margin-top:5px"><span>0%</span><b>${p.progress}% complete</b><span>100%</span></div></div><div style="height:16px"></div><div class="card pad"><div class="section-title">Stage-by-stage visibility</div><div class="timeline">${p.timeline.map((t,i)=>`<div class="step ${t.status==='Done'?'done':t.status==='In Progress'?'current':''}"><div class="step-dot">${t.status==='Done'?'✓':i+1}</div><div class="step-body"><div class="step-title">${t.stage}</div><div class="step-meta">${t.status} • ${t.time}</div></div></div>`).join('')}</div></div><div style="height:16px"></div><div class="card pad"><div class="section-title">Current blocker</div><div class="notice ${p.blocker!=='None'?'warning':''}">${escapeHtml(p.blocker)}</div></div></div></div>`;}
}
function closeDrawer(){const r=document.getElementById('drawer-root');if(r)r.innerHTML='';}

function createOrder(event,submit){const form=document.getElementById('order-form');if(!form)return;if(event)event.preventDefault();const fd=new FormData(form),p=product(fd.get('product')),qty=Number(fd.get('qty')),rate=Number(fd.get('rate')),discount=Number(fd.get('discount')||0),subtotal=qty*rate,tax=Math.round((subtotal-discount)*.18),freight=qty*1200,total=subtotal-discount+tax+freight,id=`SO-2026-${10500+APP.db.orders.length+1}`,isSubmit=submit===true;const o={id,sapNo:'',source:'PORTAL',customerId:fd.get('customer'),customerPO:fd.get('po'),orderDate:fd.get('orderDate'),deliveryDate:fd.get('delivery'),plant:fd.get('plant'),subtotal,discount,tax,freight,total,orderStatus:isSubmit?'Approval':'Draft',approvalStatus:isSubmit?'STAGE_1_PENDING':'DRAFT',currentStage:isSubmit?1:null,syncStatus:'NOT_SYNCED',createdBy:APP.state.user.name,items:[{productId:p.id,qty,rate,discount,tax:18}]};APP.db.orders.push(o);audit(o.id,isSubmit?'Submitted for Stage 1 Approval':'Order Created',APP.state.user.name);if(isSubmit)APP.db.approvals.push({id:'AP-'+Date.now(),orderId:o.id,stage:1,role:'Sales Manager',status:'PENDING',user:'',date:'',time:'',comments:''});saveDB();closeModal();toast(isSubmit?'Order submitted to Sales Manager':'Draft saved');render();}
function addCustomer(e){e.preventDefault();const fd=new FormData(e.target),id=`C${String(APP.db.customers.length+1).padStart(3,'0')}`;APP.db.customers.push({id,code:`CUST-${1000+APP.db.customers.length+1}`,name:fd.get('name'),gst:fd.get('gst'),city:fd.get('city'),terms:fd.get('terms'),owner:APP.state.user.name,status:'Active',outstanding:0});saveDB();closeModal();toast('Customer added');render();}
function addEnquiry(e){e.preventDefault();const fd=new FormData(e.target),id=`ENQ-2026-${String(300+APP.db.enquiries.length+1).padStart(5,'0')}`;APP.db.enquiries.push({id,customerId:fd.get('customer'),date:fd.get('date'),requirement:fd.get('requirement'),status:'New',owner:APP.state.user.name});saveDB();closeModal();toast('Enquiry created');render();}
function addQuotation(e){e.preventDefault();const fd=new FormData(e.target),enq=APP.db.enquiries.find(x=>x.id===fd.get('enquiry')),id=`QT-2026-${String(600+APP.db.quotations.length+1).padStart(5,'0')}`;APP.db.quotations.push({id,enquiry:enq.id,customerId:enq.customerId,date:fd.get('date'),validity:fd.get('validity'),total:Number(fd.get('total')),status:'Draft',owner:APP.state.user.name});saveDB();closeModal();toast('Quotation created');render();}
function approvalAction(id,result){const o=APP.db.orders.find(x=>x.id===id);if(!o||!o.currentStage)return;const stageByRole={'Sales Manager':1,'Production':2,'Management':3};if(stageByRole[APP.state.user.role]!==o.currentStage){toast('Only the current approver can action this stage','error');return;}const s=o.currentStage,a=APP.db.approvals.find(x=>x.orderId===id&&x.stage===s);if(a){a.status=result;a.user=APP.state.user.name;a.date=nowDate();a.time=nowTime();a.comments=result==='APPROVED'?'Approved.':result==='REJECTED'?'Rejected.':'Sent back for correction.';}audit(id,`Stage ${s} ${result}`,APP.state.user.name);if(result==='APPROVED'&&s<3){o.currentStage=s+1;o.approvalStatus=`STAGE_${s+1}_PENDING`;o.orderStatus='Approval';APP.db.approvals.push({id:'AP-'+Date.now(),orderId:id,stage:s+1,role:['','Sales Manager','Production','Management'][s+1],status:'PENDING',user:'',date:'',time:'',comments:''});}else if(result==='APPROVED'){o.currentStage=null;o.approvalStatus='APPROVED';o.orderStatus='Approved';syncPortalOrderToSAP(o);}else if(result==='REJECTED'){o.currentStage=null;o.approvalStatus='REJECTED';o.orderStatus='Rejected';}else{o.currentStage=s;o.approvalStatus=`STAGE_${s}_PENDING`;o.orderStatus='Sent Back';}saveDB();closeModal();toast(result==='APPROVED'?'Approval recorded':result==='REJECTED'?'Order rejected':'Order sent back');render();}
function syncPortalOrderToSAP(o){o.syncStatus='NOT_CONFIGURED_FOR_CREATE';audit(o.id,'Portal order approved; SAP creation endpoint not configured','System');saveDB();toast('Portal order approved; SAP creation API is not configured for this read-only integration.','warning');}
function advanceProduction(id){const p=APP.db.production.find(x=>x.id===id);if(!p)return;const stages=['Planned','Raw Material Allocated','Scheduled','In Production','Quality Inspection','Ready for Dispatch'];const idx=stages.indexOf(p.status);const n=Math.min(idx+1,stages.length-1);p.status=stages[n];p.progress=[5,18,30,62,82,100][n];p.produced=Math.round(p.qty*p.progress/100*10)/10;p.pending=Math.max(0,Math.round((p.qty-p.produced)*10)/10);p.blocker=p.status==='Raw Material Allocated'?'None':p.blocker;p.lastUpdate=`${nowDate()} ${nowTime()}`;p.timeline=p.timeline.map((t,i)=>({...t,status:i<n?'Done':i===n?'In Progress': 'Pending',time:i<=n?nowTime():'—'}));saveDB();toast(`${id} advanced to ${p.status}`);render();closeDrawer();}
function setQuality(id){const q=APP.db.quality.find(x=>x.id===id);if(!q)return;q.result='Passed';q.reviewer=APP.state.user.name;q.date=nowDate();saveDB();toast(`${id} marked Passed`);render();}
function addProduction(e){e.preventDefault();const fd=new FormData(e.target),order=APP.db.orders.find(x=>x.id===fd.get('order')),id=`PR-${Date.now().toString().slice(-6)}`;APP.db.production.push({id,orderId:order.id,productId:fd.get('product'),qty:Number(fd.get('qty')),produced:0,pending:Number(fd.get('qty')),plant:fd.get('plant'),planned:fd.get('planned'),eta:fd.get('planned'),status:'Planned',progress:5,machine:'PM-01',shift:'A',operator:APP.state.user.name,rawMaterial:'Allocated',blocker:'None',lastUpdate:`${nowDate()} ${nowTime()}`,timeline:[{stage:'Order Released',status:'Done',time:nowTime()},{stage:'Raw Material Allocated',status:'In Progress',time:'—'},{stage:'Production Scheduled',status:'Pending',time:'—'},{stage:'In Production',status:'Pending',time:'—'},{stage:'Quality Inspection',status:'Pending',time:'—'},{stage:'Ready for Dispatch',status:'Pending',time:'—'}]});saveDB();closeModal();toast('Production request created');render();}
function addQuality(e){e.preventDefault();const fd=new FormData(e.target),id=`QC-${String(APP.db.quality.length+1).padStart(3,'0')}`;APP.db.quality.push({id,orderId:fd.get('order'),gsm:fd.get('gsm'),grade:fd.get('grade'),size:fd.get('size'),result:fd.get('result'),reviewer:'',date:''});saveDB();closeModal();toast('Technical check created');render();}
function addDispatch(e){e.preventDefault();const fd=new FormData(e.target),o=APP.db.orders.find(x=>x.id===fd.get('order'));const id=`DSP-${Date.now().toString().slice(-6)}`;APP.db.dispatches.push({id,orderId:o.id,customerId:o.customerId,qty:Number(fd.get('qty')),vehicle:fd.get('vehicle'),transporter:fd.get('transporter'),date:fd.get('date'),status:'Ready'});saveDB();closeModal();toast('Dispatch created');render();}
function addDelivery(e){e.preventDefault();const fd=new FormData(e.target),o=APP.db.orders.find(x=>x.id===fd.get('order')),qty=Number(fd.get('qty')),total=o.items.reduce((a,x)=>a+x.qty,0),already=APP.db.deliveries.filter(x=>x.orderId===o.id).reduce((a,x)=>a+x.delivered,0),pending=Math.max(0,total-already-qty),id=`DEL-${Date.now().toString().slice(-6)}`;APP.db.deliveries.push({id,orderId:o.id,customerId:o.customerId,delivered:qty,pending,date:fd.get('date'),status:pending?'Partially Delivered':'Delivered',pod:fd.get('pod')});o.orderStatus=pending?'Partially Delivered':'Delivered';saveDB();closeModal();toast('Delivery recorded');render();}
function addInvoice(e){e.preventDefault();const fd=new FormData(e.target),o=APP.db.orders.find(x=>x.id===fd.get('order')),id=`INV-${50050+APP.db.invoices.length}`;APP.db.invoices.push({id,invoiceNo:`INV/26-27/${50050+APP.db.invoices.length}`,orderId:o.id,customerId:o.customerId,amount:Number(fd.get('amount')),due:fd.get('due'),paid:0,status:'Generated'});saveDB();closeModal();toast('Invoice generated');render();}
function addPayment(e){e.preventDefault();const fd=new FormData(e.target),inv=APP.db.invoices.find(x=>x.id===fd.get('invoice')),amount=Math.min(Number(fd.get('amount')),inv.amount-inv.paid);inv.paid+=amount;inv.status=inv.paid>=inv.amount?'Paid':'Partially Paid';APP.db.payments.push({id:`PAY-${90050+APP.db.payments.length}`,invoiceId:inv.id,amount,date:fd.get('date'),mode:fd.get('mode'),reference:fd.get('reference')});saveDB();closeModal();toast('Payment recorded');render();}
function exportCSV(){const rows=[['Order','SAP','Customer','Source','Value','Approval','Status'],...APP.db.orders.map(o=>[o.id,o.sapNo,customer(o.customerId).name,o.source,o.total,o.approvalStatus,o.orderStatus])];const csv=rows.map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='greenpaper-sales-orders.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('CSV exported');}
function resetDemo(){localStorage.removeItem(DB_KEY);APP.db=loadDB();APP.state.search='';APP.state.filters={};toast('Demo data reset');render();}
function login(e){e.preventDefault();const fd=new FormData(e.target),email=String(fd.get('email')).toLowerCase().trim(),password=String(fd.get('password')),u=getUsers().find(x=>x.email.toLowerCase()===email&&x.password===password);if(!u){toast('No matching signed-up account found','error');return;}saveAuth({name:u.name,email:u.email,role:u.role,createdAt:u.createdAt});go('dashboard');}
function signup(e){e.preventDefault();const fd=new FormData(e.target),email=String(fd.get('email')).toLowerCase().trim(),users=getUsers();if(users.some(x=>x.email.toLowerCase()===email)){toast('An account with this email already exists','error');return;}const user={name:fd.get('name'),email,password:fd.get('password'),role:fd.get('role'),createdAt:nowDate()};users.push(user);setUsers(users);toast('Account created. Please log in.');go('login');}
function logout(){saveAuth(null);go('login');}

document.addEventListener('click',e=>{const modal=e.target.closest('[data-modal]');if(modal){openModal(modal.dataset.modal,modal.dataset.id);return;}const drawer=e.target.closest('[data-drawer]');if(drawer){openDrawer(drawer.dataset.drawer,drawer.dataset.id);return;}});

document.getElementById('app').innerHTML='';
render();
startSapAutoSync();
